// ============================================================
// EASTER EGGS — "bí mật nhỏ" của mỗi kết quả, seeded theo resultId
// nên share cho nhau sẽ thấy khác nhau nhưng cố định lại nếu xem lại
// cùng 1 kết quả. Tách riêng khỏi jadeContent.ts như đề xuất — không
// liên quan classification/pricing, thuần presentation.
// ============================================================

export const EASTER_EGGS = {
  cafe: [
    "Có những chiếc vòng nhìn trong nhà bình thường, bước ra nắng lại như đổi tính.",
    "Ngọc đẹp hiếm khi là màu đầu tiên bạn thích. Thường là màu thứ hai bạn quay lại nhìn.",
    "Tử La Lan là kiểu màu càng nhìn dưới nắng càng có chuyện để kể.",
    "Đế Vương Lục không cần quá sáng. Nó cần đủ 'đứng'.",
    "Mỗi người sẽ thấy cùng một chiếc vòng hơi khác nhau dưới ánh sáng khác nhau.",
    "Một chiếc vòng hợp tay đôi khi quan trọng hơn một chiếc vòng đắt.",
    "Có những chiếc ngọc chụp ảnh không đẹp, nhưng đeo ngoài đời rất cuốn.",
    "Ánh sáng vàng và ánh sáng trắng là hai bài kiểm tra hoàn toàn khác nhau.",
    "Màu càng đồng đều chưa chắc càng thú vị.",
    "Đừng chọn chiếc vòng chỉ vì trend. Chọn chiếc làm bạn muốn đeo mỗi ngày.",
    "Ngọc cũng có 'mood lighting'.",
    "Chiếc vòng càng có chiều sâu càng khó chụp đúng màu.",
    "Có người mê ngọc trong. Có người mê ngọc có chuyện.",
    "Một ít hoa bay đúng chỗ còn đáng nhớ hơn một mảng màu hoàn hảo.",
    "Đừng soi ngọc quá gần. Lùi lại nửa bước sẽ thấy tổng thể.",
    "Chiếc vòng đẹp nhất không phải lúc mới mua, mà là lúc đã quen tay.",
    "Ngọc không có filter ngoài đời.",
    "Có những chiếc vòng hợp ảnh, có chiếc hợp người.",
    "Nếu bạn cứ quay lại nhìn một chiếc nhiều lần, thường là có lý do.",
    "Màu tím của phỉ thúy rất biết 'đổi mood'.",
    "Có chiếc ngọc nhìn lạnh, nhưng đeo lên tay lại rất ấm.",
    "Ngọc cũng có ngày đẹp trời và ngày nhiều mây.",
    "Đeo ngọc lâu sẽ nhớ cảm giác của nó hơn nhớ giá của nó.",
    "Một chiếc vòng có thể rất yên lặng nhưng vẫn rất có gu.",
    "Đừng vội kết luận màu trong 3 giây đầu tiên.",
  ],
  rumor: [
    "Hoa bay đẹp khi nó có bố cục. Không phải càng nhiều càng đẹp.",
    "Sớ bông là đặc điểm bị nhầm với nứt nhiều nhất.",
    "Đường chỉ màu thường để ánh sáng đi xuyên qua, còn nứt thì cắt ánh sáng.",
    "Một chiếc vòng có thể có nhiều màu mà vẫn rất hài hòa.",
    "Độ trong và màu là hai câu chuyện khác nhau.",
    "Cùng một màu xanh vẫn có thể thuộc nhiều chủng khác nhau.",
    "Đậu không có nghĩa là ngọc xấu. Nó chỉ nói về cấu trúc.",
    "Nếp Băng nổi tiếng vì cảm giác 'mượt', không phải vì trong nhất.",
    "Băng không phải lúc nào cũng đắt hơn Cao Băng nếu màu khác nhau.",
    "Mắt cát đẹp hay không phụ thuộc rất nhiều vào vị trí.",
    "Một ít tạp chất không tự động làm viên ngọc mất giá trị.",
    "Ngọc càng tự nhiên càng có nhiều chi tiết để quan sát.",
    "Có những đường gân chỉ là cấu trúc, không phải hư hại.",
    "Sớ ngang luôn đáng để nhìn kỹ vị trí của nó.",
    "Không phải mọi đường trắng đều là nứt.",
    "Độ sạch là một yếu tố, không phải toàn bộ câu chuyện.",
    "Màu loang đẹp là loang có chủ ý của tự nhiên.",
    "Hai chiếc vòng cùng tên màu vẫn có thể rất khác nhau.",
    "Ánh sáng giúp thấy cấu trúc, không giúp đoán nguồn gốc.",
    "Chủng nói về cốt ngọc. Màu nói về diện ngọc.",
    "Một chiếc vòng nhiều hoa bay thường không có bản sao y hệt.",
    "Có những chiếc ngọc càng soi càng thấy thêm màu.",
    "Đừng đánh giá ngọc chỉ bằng ảnh studio.",
    "Một chiếc vòng đẹp là tổng hòa nhiều yếu tố.",
    "Không có viên ngọc nào hoàn toàn giống viên nào.",
  ],
  grandma: [
    "Chiếc này là kiểu đeo ba năm vẫn thấy hợp mình.",
    "Đẹp kiểu không cần ai khen.",
    "Càng nhìn càng thấy hiền.",
    "Đeo đi làm cũng được, đi ăn cưới cũng được.",
    "Kiểu vòng ít lỗi mốt.",
    "Có nét dịu nhưng không nhạt.",
    "Đây là kiểu bà cất trong hộp gỗ.",
    "Đeo mùa nào cũng hợp.",
    "Nhìn có cảm giác mát tay.",
    "Kiểu vòng mặc áo trắng rất đẹp.",
    "Cổ tay nhỏ đeo vẫn có hiện diện.",
    "Không phô trương nhưng có khí chất.",
    "Càng lớn tuổi càng dễ thích kiểu này.",
    "Đeo lâu sẽ thành món quen.",
    "Nhìn là biết người chọn có gu.",
    "Đây là kiểu vòng không cần nhiều phụ kiện.",
    "Hợp người thích tối giản.",
    "Có vẻ đẹp rất bình tĩnh.",
    "Đẹp kiểu nhìn gần mới thấy.",
    "Đeo hàng ngày không chán.",
    "Không phải nổi bật nhất, nhưng dễ ở lại lâu nhất.",
    "Kiểu vòng ít phải suy nghĩ phối đồ.",
    "Càng ngắm càng mềm.",
    "Có cảm giác rất 'người nhà'.",
    "Bà ngoại gật đầu.",
  ],
  learn: [
    "Độ trong cao không đồng nghĩa màu sẽ đẹp hơn.",
    "Vi hạt càng mịn, ánh sáng thường đi vào lòng ngọc mềm hơn.",
    "Nếp Băng khác Băng ở cấu trúc và độ trong, không phải ở màu.",
    "Hoa bay là bố cục màu, không phải một loại màu riêng.",
    "Đường chỉ màu và đường nứt nhìn giống nhau nhưng phản ứng với ánh sáng khác nhau.",
    "Độ sạch là cảm nhận thị giác của lòng ngọc.",
    "Màu phân bố đều tạo cảm giác ổn định hơn.",
    "Loang nhẹ khác loang mạnh ở cách các vùng màu chuyển tiếp.",
    "Một chiếc vòng có thể vừa có chỉ màu vừa rất sạch.",
    "Sớ bông thường tạo chiều sâu chứ không tạo cảm giác gãy.",
    "Mắt cát nằm trên bề mặt nên thường dễ nhận biết hơn.",
    "Không phải mọi đặc điểm nội tại đều ảnh hưởng độ bền.",
    "Độ dày và bản vòng là hai thông số khác nhau.",
    "Cùng ni vòng nhưng bản rộng sẽ cho cảm giác rất khác.",
    "Tím Lam và Tử La Lan là hai nhóm tím khác nhau.",
    "Đế Vương Lục thuộc nhóm màu hiếm hơn đa số các sắc lục.",
    "Bạch Nguyệt Quang không phải màu trắng đục.",
    "Trắng Cháo có cảm giác mềm hơn Bạch Nguyệt Quang.",
    "Xanh Dầu thường trầm hơn Xanh Ngọt.",
    "Thanh Thủy Lục thiên về cảm giác mát.",
    "Hoàng Tông Phỉ thuộc nhóm màu vàng của phỉ thúy.",
    "Gà Đen và Mặc Thúy không phải cùng một màu.",
    "Màu ngọc thay đổi khá nhiều theo nhiệt độ ánh sáng.",
    "Ảnh điện thoại thường làm màu ngọc bão hòa hơn ngoài đời.",
    "Giám định luôn cần nhiều thông tin hơn chỉ một bức ảnh.",
  ],
} as const;
